language: node_js
node_js:
  - 12
addons:
  packages:
    - libgconfig-2-4
cache:
  npm: true
  directories:
    - ~/.cache
script:
  - eslint 'src/**'
  - yarn test:coveralls
  - yarn test:cypress:ci
deploy:
  provider: heroku
  api_key: $HEROKU_API
  app: pareaqui-react
notifications:
  email: false
